{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "python-app.fullname" . }}-pvc
  labels:
    {{- include "python-app.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-options: Prune=false  
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}