---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: python-api-python-app-secret
  namespace: dev
spec:
  encryptedData:
    API_TOKEN: AgCanS/WronRPORUDow8cR4TIfL30eLWLNRNjp72WOMGamBr/079bpB4M+eZ++yGLyJ2RBQXiXq9NL1yltNIvi8S+NSXySthVjDP+30BIuAo8J3pkp9NCA02V12t4sNmA2aTLu/vgBRtTqOcSKsOu55x1+bF2Nkewb/y5wKt3UbGO0+65XDNONsZ3Za0/ODehpGEpR0XijgwXLdKyHs4wTfAPU0AzNCqun09/8vOkDRA6m7SUUq9RFpbVLQNXPlO3p22/gXzL0UwJUiCWs73gT8IPo4G/UlYcosC14WEC8akL5MCoS0Le4DbWkAYxKHLRankI6FYzW0oir5SkEt48SQIUqLdH8DuTVu4SXMof/w7ICz7bbGyWg6/iZ3SZkVy6SJTRcBe9NlaI+kBkTazzCKLQx1cvvdwsGj89Bs6UoczPBQ34UkyJBzPb3kz4Phg8reay7DZv3H3+mqxnl4mdBW3oizG/ntJqIlV/gdcus0fRZ8pOYmjyh93+23LrXm9IsVEWLsuBX/UoPN2KcuHqO4rWT63r/dbyy/whprpSGrbWdhL0ONfLZ5dMaHIMegqlc55DfMEfAGcjI84J7es10A47b7TVooatU/D20Iy0qTK2uvMB9XLP54iLUXQ5HqrjD6WTgLUtP75+QDwwEI1adgoGN2WSJVShdajV/nH9aTSRmkKvWKjxDUszrQsnCfZrVc4c1fid0bbd0EIFWVtyebjctpgGQ==
  template:
    metadata:
      name: python-api-python-app-secret
      namespace: dev
