apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets-k3s-lab-wsl
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/oscarHidalgo93/devops-project.git
    targetRevision: develop
    path: infra/sealed-secrets/clusters/k3s-lab-wsl
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
