replicaCount: 1

image:
  repository: python-k8s-app
  tag: "2.0"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  #nodePort: 30007

containerPort: 8080

ingress:
  enabled: false
  host: "" 
   
config:
  appName: ""
  environment: ""

secret:
  apiToken: ""

resources: 
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "100m"
    memory: "256Mi"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70    
