replicaCount: 2

image:
  repository: python-k8s-app
  tag: "2.7"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80  
  
containerPort: 8080

#Secret: en siguientes versiones se dejara de subir secretos realmente sensibles a git, esto es una prueba.
#Se recomienda usar un gestor de secretos como Hashicorp Vault o AWS Secrets Manager.
secret:
  apiToken: "dev-token-1234567890"

persistance:
  enabled: true
  size: 1Gi
  mountPath: /data
  accessMode: ReadWriteOnce

resources:
  requests:
    cpu: "100m"
    memory: "64Mi" 
  limits:
    cpu: "500m"
    memory: "256Mi"

ingress:
  enabled: true
  host: api.local  

config:
  appName: python-api
  environment: dev  

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

podSecurityContext:
  fsGroup: 10001
  seccompProfile:
    type: RuntimeDefault
    
containerSecurityContext:
  runAsNonRoot: true
  runAsUser: 10001
  runAsGroup: 10001
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL

extraVolumes:
  - name: tmp
    emptyDir: {}
    
extraVolumeMounts:
  - name: tmp
    mountPath: /tmp        

