replicaCount: 1

image:
  repository: python-k8s-app
  tag: "2.0"
  pullPolicy: IfNotPresent

#Buenas practicas de seguridad (scan de Trivy))
podSecurityContext:
  seccompProfile:
    type: RuntimeDefault
containerSecurityContext: 
  runAsNonRoot: true
  runAsUser: 10001
  runAsGroup: 10001
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL
extraVolumes: 
  - name: tmp
    emptyDir: {}
extraVolumeMounts: 
  - name: tmp
    mountPath: /tmp
  
service:
  type: NodePort
  port: 80
  #nodePort: 30007

containerPort: 8080

ingress:
  enabled: false
  host: "" 
   
config:
  appName: ""
  environment: ""

secret:
  apiToken: ""

persistance:
  enabled: false
  size: 1Gi
  mountPath: /data
  accessMode: ReadWriteOnce


resources: 
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "100m"
    memory: "256Mi"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70  
  
    
