---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: python-api-python-app-secret
  namespace: dev
spec:
  encryptedData:
    API_TOKEN: AgCvEm1JpFPv8Kiive43tZzO2WBC8XOkfqO2bpCEoJWEzUE8RW7IcDCwMxYppAofQnhoOAn4s1TAnmLPw9t8dN+UwXdXnNYw+NCiQ35XiIVVOpZfmcS6ubSQmEmkrsZLDqMyc4obGE67PBx0tSddgQW5CFceJqjx/jCtqAOrBGnQzTYtyEydTFXir8wuyHUEtYJC8ukWlkuR13r7BGfixEcu4T0OE38Y2+7s5lCwdwCfQIsCBj5OjWzlzvU9+Yqlm5QMOJe6Sh6RlPckQi2o0OL5W21ynxErFGf9FnWHBjZja0mQtumMS3T1gte0QDdghgsdOZJIwsDF8f1dERuiZaWeZuXWYJsV3VTwrCxWYWd77UuL9Pc6qS26ua96CLO8BQo6+zPD+Rr6J//BBP1b2waw4SUNk8Q3bMtWEpat6jfQlY6abJfoFNo7nnadms4Ubw6RNJ3UuartTgNFct1NFFfbsWcYN/JOu7f4BY/DZlHU/1/UnoiOD+pokn1UF7GUauotD/ixetYT+HFkzGZgnnbe5Xa3Xz2DyrWVYnN+dWTPWZV25MutDJqJ3NeTLQbGcDElb8KY0kc+Os2tSckbq0TmqrSNXG/vSjulKykqZoFd3RR88Su3xfWVTeC7MrM5aYSzL3zNS/XJX42USsI/w5PtHs6a0s71cLshqT6gLeXMiU/DS94/q66QQeo+gyvHbZfZfQNjW2rH7wooW82o1KZ7nnJ9og4=
  template:
    metadata:
      name: python-api-python-app-secret
      namespace: dev
